import cron from 'node-cron';
import { db } from '../config/firebase.js';
import {
    getNextWeekStart,
    getScheduleClock,
    getScheduleWeekKey,
    normalizeScheduleConfig
} from '../utils/scheduleConfig.js';

let schedulerStarted = false;
let schedulerTickRunning = false;
let autoGenerationTickRunning = false;

const WEEKLY_RUN_LEASE_MS = 2 * 60 * 60 * 1000;

async function claimWeeklyRun(profileId, targetWeekKey, now) {
    const runId = `weekly_${profileId}_${targetWeekKey}`;
    const ref = db.collection('schedulerRuns').doc(runId);

    const claimed = await db.runTransaction(async transaction => {
        const snapshot = await transaction.get(ref);
        const current = snapshot.exists ? snapshot.data() : null;
        const leaseUntil = current?.leaseUntil?.toDate?.() || null;

        if (['completed', 'partial', 'recovered'].includes(current?.status)) return false;
        if (current?.status === 'running' && leaseUntil && leaseUntil > now) return false;

        transaction.set(ref, {
            kind: 'weekly-generation',
            profileId,
            targetWeekKey,
            status: 'running',
            startedAt: now,
            updatedAt: now,
            leaseUntil: new Date(now.getTime() + WEEKLY_RUN_LEASE_MS),
            attempt: (current?.attempt || 0) + 1
        }, { merge: true });
        return true;
    });

    return claimed ? { id: runId, ref } : null;
}

async function finishWeeklyRun(run, result) {
    const failed = Number(result?.failed || 0);
    await run.ref.set({
        status: failed > 0 ? 'partial' : 'completed',
        generated: Number(result?.generated || 0),
        failed,
        errors: Array.isArray(result?.errors) ? result.errors.slice(0, 20) : [],
        finishedAt: new Date(),
        updatedAt: new Date(),
        leaseUntil: null
    }, { merge: true });
}

async function failWeeklyRun(run, error) {
    await run.ref.set({
        status: 'failed',
        error: error.message,
        failedAt: new Date(),
        updatedAt: new Date(),
        leaseUntil: null
    }, { merge: true });
}

/**
 * Inicia o scheduler para sincronizar jobs externos do Upload-Post
 * e disparar geração automática semanal de conteúdo.
 */
export function startScheduler() {
    if (process.env.ENABLE_IN_PROCESS_SCHEDULER !== 'true') {
        console.log('ℹ️ Scheduler interno desativado; aguardando gatilho externo protegido.');
        return;
    }
    if (schedulerStarted) {
        console.log('ℹ️ Scheduler já estava iniciado. Ignorando nova inicialização.');
        return;
    }

    schedulerStarted = true;
    console.log('⏰ Scheduler iniciado - sincronizando Upload-Post a cada minuto');

    // Executa a cada minuto — sincroniza jobs externos e roda auto-generate
    cron.schedule('* * * * *', async () => {
        if (schedulerTickRunning) {
            console.log('⏳ Scheduler anterior ainda em execução. Pulando este ciclo.');
            return;
        }

        schedulerTickRunning = true;
        try {
            const { syncScheduledPosts } = await import('./postService.js');
            await syncScheduledPosts();
        } catch (error) {
            console.error('❌ Erro no scheduler:', error);
        } finally {
            schedulerTickRunning = false;
        }
    });

    // A geração de IA não bloqueia a sincronização/publicação que roda acima.
    cron.schedule('* * * * *', () => {
        runWeeklyAutoGeneration().catch(error => {
            console.error('❌ Erro no gerador semanal:', error);
        });
    });
}

/**
 * Busca todos os perfis com autoGenerate habilitado e gera o plano da semana
 */
export async function runWeeklyAutoGeneration() {
    if (autoGenerationTickRunning) {
        return;
    }

    autoGenerationTickRunning = true;

    // Importação dinâmica para evitar dependência circular
    const { generateWeeklyPlan } = await import('./contentGeneratorService.js');

    try {
        const now = new Date();

        // Busca todos para manter compatibilidade com perfis que ainda não têm
        // autoGenerationEnabled persistido. A normalização traduz o modo legado.
        const snapshot = await db.collection('businessProfiles').get();

        if (snapshot.empty) {
            return;
        }

        for (const doc of snapshot.docs) {
            const profile = { id: doc.id, ...doc.data() };
            const schedule = normalizeScheduleConfig(profile.contentSchedule || {});
            if (!schedule.autoGenerationEnabled) continue;

            const { dayName: todayName, time: currentTime } = getScheduleClock(now, schedule.timezone);
            const currentWeekKey = getScheduleWeekKey(now, schedule.timezone);
            const autoDay = schedule.autoGenerateDay || 'sunday';
            const autoTime = schedule.autoGenerateTime || '20:00';
            const alreadyGeneratedThisWeek = schedule.lastAutoGeneratedWeek === currentWeekKey;

            if (autoDay !== todayName) continue;
            if (currentTime < autoTime) continue;
            if (alreadyGeneratedThisWeek) continue;

            try {
                const nextWeekStartDate = getNextWeekStart(now, schedule.timezone);
                const targetWeekKey = getScheduleWeekKey(nextWeekStartDate, schedule.timezone);
                const run = await claimWeeklyRun(doc.id, targetWeekKey, now);
                if (!run) continue;
                console.log(`🚀 [auto-generate] Gerando plano adiantado para "${profile.name}" (${doc.id}) a partir de: ${nextWeekStartDate.toLocaleDateString('pt-BR')}`);
                const result = await generateWeeklyPlan(doc.id, nextWeekStartDate, null, {}, progress => {
                    run.ref.set({
                        heartbeatAt: new Date(),
                        progress,
                        updatedAt: new Date(),
                    }, { merge: true }).catch(error => console.warn('⚠️ Falha ao atualizar heartbeat:', error.message));
                }, {
                    generationRunId: run.id,
                    targetWeekKey,
                });
                await finishWeeklyRun(run, result);
                await db.collection('businessProfiles').doc(doc.id).update({
                    'contentSchedule.lastAutoGeneratedAt': now,
                    'contentSchedule.lastAutoGeneratedWeek': currentWeekKey,
                    'contentSchedule.lastAutoGenerationStatus': result.failed > 0 ? 'partial' : 'completed',
                    'contentSchedule.lastAutoGenerationStats': {
                        generated: result.generated,
                        failed: result.failed
                    },
                    updatedAt: now
                });
                console.log(`✅ [auto-generate] "${profile.name}": ${result.generated} gerados, ${result.failed} erros`);
            } catch (err) {
                const targetWeekKey = getScheduleWeekKey(getNextWeekStart(now, schedule.timezone), schedule.timezone);
                const runRef = db.collection('schedulerRuns').doc(`weekly_${doc.id}_${targetWeekKey}`);
                await failWeeklyRun({ ref: runRef }, err);
                console.error(`❌ [auto-generate] Erro em "${profile.name}": ${err.message}`);
            }
        }
    } finally {
        autoGenerationTickRunning = false;
    }
}

const EXTERNAL_TICK_LEASE_MS = 4 * 60 * 1000;

async function claimExternalTick(now = new Date()) {
    const ref = db.collection('schedulerRuns').doc('uptimerobot_tick');
    return db.runTransaction(async transaction => {
        const snapshot = await transaction.get(ref);
        const current = snapshot.exists ? snapshot.data() : {};
        const leaseUntil = current.leaseUntil?.toDate?.() || null;
        if (current.status === 'running' && leaseUntil && leaseUntil > now) return false;
        transaction.set(ref, {
            kind: 'external-tick',
            status: 'running',
            startedAt: now,
            heartbeatAt: now,
            updatedAt: now,
            leaseUntil: new Date(now.getTime() + EXTERNAL_TICK_LEASE_MS),
            attempt: Number(current.attempt || 0) + 1,
        }, { merge: true });
        return true;
    });
}

async function executeExternalTick() {
    const ref = db.collection('schedulerRuns').doc('uptimerobot_tick');
    try {
        const { syncScheduledPosts } = await import('./postService.js');
        await syncScheduledPosts();
        await ref.set({ heartbeatAt: new Date(), updatedAt: new Date() }, { merge: true });

        // Rede de segurança da revisão: aprova sozinho o que ninguém revisou a tempo.
        // Isolado para que uma falha aqui não impeça a geração semanal abaixo.
        try {
            const { runAutoApprover } = await import('../cron/autoApprover.js');
            await runAutoApprover();
        } catch (approverError) {
            console.error('❌ Auto-aprovador falhou:', approverError);
        }

        await runWeeklyAutoGeneration();
        await ref.set({
            status: 'completed',
            finishedAt: new Date(),
            heartbeatAt: new Date(),
            updatedAt: new Date(),
            leaseUntil: null,
            error: null,
        }, { merge: true });
    } catch (error) {
        await ref.set({
            status: 'failed',
            error: error.message,
            failedAt: new Date(),
            updatedAt: new Date(),
            leaseUntil: null,
        }, { merge: true }).catch(() => {});
        console.error('❌ Tick externo falhou:', error);
    }
}

export async function dispatchExternalSchedulerTick() {
    const claimed = await claimExternalTick();
    if (!claimed) return { accepted: false, reason: 'tick-already-running' };
    setImmediate(() => executeExternalTick());
    return { accepted: true, runId: 'uptimerobot_tick' };
}
