import cron from 'node-cron';
import { db } from '../config/firebase.js';

let schedulerStarted = false;
let schedulerTickRunning = false;
let autoGenerationTickRunning = false;

const DAY_NAMES = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

function getCurrentDayName(now = new Date()) {
    return DAY_NAMES[now.getDay()];
}

function getCurrentTimeHHMM(now = new Date()) {
    return `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
}

function getWeekKey(now = new Date()) {
    const date = new Date(now);
    const day = date.getDay();
    const diffToMonday = day === 0 ? -6 : 1 - day;
    date.setDate(date.getDate() + diffToMonday);
    date.setHours(0, 0, 0, 0);
    return date.toISOString().slice(0, 10);
}

/**
 * Inicia o scheduler para sincronizar jobs externos do Upload-Post
 * e disparar geração automática semanal de conteúdo.
 */
export function startScheduler() {
    if (schedulerStarted) {
        console.log('ℹ️ Scheduler já estava iniciado. Ignorando nova inicialização.');
        return;
    }

    schedulerStarted = true;
    console.log('⏰ Scheduler iniciado - sincronizando Upload-Post a cada minuto');

    // Executa a cada minuto — sincroniza jobs externos e roda auto-generate
    cron.schedule('* * * * *', async () => {
        if (schedulerTickRunning) {
            console.log('⏳ Scheduler anterior ainda em execução. Pulando este ciclo.');
            return;
        }

        schedulerTickRunning = true;
        try {
            // Sync posts agendados externamente
            const { syncScheduledPosts, getReadyPosts, executePost } = await import('./postService.js');
            await syncScheduledPosts();

            // Processar posts pendentes locais
            const readyPosts = await getReadyPosts();
            if (readyPosts.length > 0) {
                console.log(`⚡ Encontrados ${readyPosts.length} posts pendentes para publicar localmente!`);
                for (const post of readyPosts) {
                    console.log(`▶️ Iniciando post pendente ${post.id}`);
                    await executePost(post.id);
                }
            }

            await runWeeklyAutoGeneration();

            // Executar auto-aprovação de segurança a cada 15 minutos
            if (new Date().getMinutes() % 15 === 0) {
                try {
                    const { runAutoApprover } = await import('../cron/autoApprover.js');
                    await runAutoApprover();
                } catch (approveErr) {
                    console.error('❌ Erro ao rodar auto-aprovação no scheduler:', approveErr);
                }
            }

        } catch (error) {
            console.error('❌ Erro no scheduler:', error);
        } finally {
            schedulerTickRunning = false;
        }
    });
}

/**
 * Busca todos os perfis com autoGenerate habilitado e gera o plano da semana
 */
async function runWeeklyAutoGeneration() {
    if (autoGenerationTickRunning) {
        return;
    }

    autoGenerationTickRunning = true;

    // Importação dinâmica para evitar dependência circular
    const { generateWeeklyPlan } = await import('./contentGeneratorService.js');

    try {
        const now = new Date();
        const todayName = getCurrentDayName(now);
        const currentTime = getCurrentTimeHHMM(now);
        const currentWeekKey = getWeekKey(now);

        // Busca todos os perfis que têm autoGenerate ativo
        const snapshot = await db.collection('businessProfiles')
            .where('contentSchedule.autonomyMode', '==', 'auto')
            .get();

        if (snapshot.empty) {
            return;
        }

        for (const doc of snapshot.docs) {
            const profile = { id: doc.id, ...doc.data() };
            const schedule = profile.contentSchedule || {};
            const autoDay = schedule.autoGenerateDay || 'sunday';
            const autoTime = schedule.autoGenerateTime || '20:00';
            const alreadyGeneratedThisWeek = schedule.lastAutoGeneratedWeek === currentWeekKey;

            if (autoDay !== todayName) continue;
            if (currentTime < autoTime) continue;
            if (alreadyGeneratedThisWeek) continue;

            try {
                // Desloca o início da geração semanal automática em 7 dias para programar a próxima semana (1 semana de antecedência)
                const nextWeekStartDate = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
                console.log(`🚀 [auto-generate] Gerando plano adiantado para "${profile.name}" (${doc.id}) a partir de: ${nextWeekStartDate.toLocaleDateString('pt-BR')}`);
                const result = await generateWeeklyPlan(doc.id, nextWeekStartDate);
                await db.collection('businessProfiles').doc(doc.id).update({
                    contentSchedule: {
                        ...schedule,
                        lastAutoGeneratedAt: now,
                        lastAutoGeneratedWeek: currentWeekKey
                    },
                    updatedAt: now
                });
                console.log(`✅ [auto-generate] "${profile.name}": ${result.generated} gerados, ${result.failed} erros`);
            } catch (err) {
                console.error(`❌ [auto-generate] Erro em "${profile.name}": ${err.message}`);
            }
        }
    } finally {
        autoGenerationTickRunning = false;
    }
}
