export const DEFAULT_SCHEDULE_TIMEZONE = 'America/Sao_Paulo';

const DAY_NAMES = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
const DEFAULT_CONTENT_SCHEDULE = {
    postsPerWeek: 5,
    storiesPerWeek: 7,
    preferredDays: ['tuesday', 'thursday', 'saturday'],
    preferredTimes: ['09:00', '18:00'],
    storyPreferredDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    storyPreferredTimes: ['08:00', '20:00'],
    reuseStories: true,
    storyReuseCooldownDays: 14,
    autoGenerateDay: 'sunday',
    autoGenerateTime: '20:00'
};

export function normalizeScheduleConfig(schedule = {}) {
    const legacyMode = ['manual', 'review', 'auto'].includes(schedule.autonomyMode)
        ? schedule.autonomyMode
        : 'review';
    const publishingMode = ['review', 'auto'].includes(schedule.publishingMode)
        ? schedule.publishingMode
        : (legacyMode === 'auto' ? 'auto' : 'review');
    const autoGenerationEnabled = typeof schedule.autoGenerationEnabled === 'boolean'
        ? schedule.autoGenerationEnabled
        : legacyMode !== 'manual';

    return {
        ...DEFAULT_CONTENT_SCHEDULE,
        ...schedule,
        autoGenerationEnabled,
        publishingMode,
        // Mantido enquanto clientes antigos ainda enviam/leem este campo.
        autonomyMode: autoGenerationEnabled ? publishingMode : 'manual',
        timezone: isValidTimeZone(schedule.timezone)
            ? schedule.timezone
            : DEFAULT_SCHEDULE_TIMEZONE
    };
}

export function isValidTimeZone(timeZone) {
    if (typeof timeZone !== 'string' || !timeZone.trim()) return false;
    try {
        new Intl.DateTimeFormat('en-US', { timeZone }).format(new Date());
        return true;
    } catch {
        return false;
    }
}

export function getZonedDateParts(date = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = new Intl.DateTimeFormat('en-US', {
        timeZone,
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hourCycle: 'h23'
    }).formatToParts(date).reduce((result, part) => {
        if (part.type !== 'literal') result[part.type] = Number(part.value);
        return result;
    }, {});

    const calendarDate = new Date(Date.UTC(parts.year, parts.month - 1, parts.day));
    return {
        ...parts,
        dayName: DAY_NAMES[calendarDate.getUTCDay()]
    };
}

export function zonedDateTimeToUtc({ year, month, day, hour = 0, minute = 0, second = 0 }, timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const targetAsUtc = Date.UTC(year, month - 1, day, hour, minute, second);
    let result = new Date(targetAsUtc);

    // Duas passagens cobrem mudanças de offset próximas a transições de horário de verão.
    for (let attempt = 0; attempt < 2; attempt++) {
        const observed = getZonedDateParts(result, timeZone);
        const observedAsUtc = Date.UTC(
            observed.year,
            observed.month - 1,
            observed.day,
            observed.hour,
            observed.minute,
            observed.second
        );
        result = new Date(result.getTime() + (targetAsUtc - observedAsUtc));
    }

    return result;
}

function addCalendarDays(parts, days) {
    const date = new Date(Date.UTC(parts.year, parts.month - 1, parts.day + days));
    return {
        year: date.getUTCFullYear(),
        month: date.getUTCMonth() + 1,
        day: date.getUTCDate()
    };
}

export function getScheduleClock(now = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = getZonedDateParts(now, timeZone);
    return {
        dayName: parts.dayName,
        time: `${String(parts.hour).padStart(2, '0')}:${String(parts.minute).padStart(2, '0')}`
    };
}

export function getScheduleWeekKey(now = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = getZonedDateParts(now, timeZone);
    const calendarDate = new Date(Date.UTC(parts.year, parts.month - 1, parts.day));
    const day = calendarDate.getUTCDay();
    const monday = addCalendarDays(parts, day === 0 ? -6 : 1 - day);
    return `${monday.year}-${String(monday.month).padStart(2, '0')}-${String(monday.day).padStart(2, '0')}`;
}

export function getNextWeekStart(now = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = getZonedDateParts(now, timeZone);
    const calendarDate = new Date(Date.UTC(parts.year, parts.month - 1, parts.day));
    const day = calendarDate.getUTCDay();
    const daysUntilNextMonday = day === 0 ? 1 : 8 - day;
    const nextMonday = addCalendarDays(parts, daysUntilNextMonday);
    return zonedDateTimeToUtc(nextMonday, timeZone);
}

export function addDaysInTimeZone(date, days, timeZone = DEFAULT_SCHEDULE_TIMEZONE, time = '00:00') {
    const parts = getZonedDateParts(date, timeZone);
    const target = addCalendarDays(parts, days);
    const [hour, minute] = time.split(':').map(Number);
    return zonedDateTimeToUtc({ ...target, hour, minute }, timeZone);
}
