export const DEFAULT_SCHEDULE_TIMEZONE = 'America/Sao_Paulo';

const DAY_NAMES = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
const DEFAULT_CONTENT_SCHEDULE = {
    postsPerWeek: 5,
    storiesPerWeek: 7,
    preferredDays: ['tuesday', 'thursday', 'saturday'],
    preferredTimes: ['09:00', '18:00'],
    storyPreferredDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    storyPreferredTimes: ['08:00', '20:00'],
    reuseStories: true,
    storyReuseCooldownDays: 14,
    autoGenerateDay: 'sunday',
    autoGenerateTime: '20:00',
    autoApproveFallbackEnabled: true,
    autoApproveLeadHours: 24,
    publishingMode: 'auto'
};

export function normalizeScheduleConfig(schedule = {}) {
    const legacyMode = ['manual', 'review', 'auto'].includes(schedule.autonomyMode)
        ? schedule.autonomyMode
        : 'auto';
    const publishingMode = ['review', 'auto'].includes(schedule.publishingMode)
        ? schedule.publishingMode
        : (legacyMode === 'review' ? 'review' : 'auto');
    const autoGenerationEnabled = typeof schedule.autoGenerationEnabled === 'boolean'
        ? schedule.autoGenerationEnabled
        : legacyMode !== 'manual';

    // Rede de segurança da revisão: ativada por padrão quando o modo de publicação é 'auto',
    // ou se ativada explicitamente no perfil.
    const autoApproveFallbackEnabled = typeof schedule.autoApproveFallbackEnabled === 'boolean'
        ? schedule.autoApproveFallbackEnabled
        : (publishingMode === 'auto');
    const parsedLeadHours = Number(schedule.autoApproveLeadHours);
    const autoApproveLeadHours = Number.isFinite(parsedLeadHours) && parsedLeadHours > 0
        ? Math.min(parsedLeadHours, 168)
        : DEFAULT_CONTENT_SCHEDULE.autoApproveLeadHours;

    return {
        ...DEFAULT_CONTENT_SCHEDULE,
        ...schedule,
        autoGenerationEnabled,
        publishingMode,
        autoApproveFallbackEnabled,
        autoApproveLeadHours,
        // Mantido enquanto clientes antigos ainda enviam/leem este campo.
        autonomyMode: autoGenerationEnabled ? publishingMode : 'manual',
        timezone: isValidTimeZone(schedule.timezone)
            ? schedule.timezone
            : DEFAULT_SCHEDULE_TIMEZONE
    };
}

export function isValidTimeZone(timeZone) {
    if (typeof timeZone !== 'string' || !timeZone.trim()) return false;
    try {
        new Intl.DateTimeFormat('en-US', { timeZone }).format(new Date());
        return true;
    } catch {
        return false;
    }
}

export function getZonedDateParts(date = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = new Intl.DateTimeFormat('en-US', {
        timeZone,
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hourCycle: 'h23'
    }).formatToParts(date).reduce((result, part) => {
        if (part.type !== 'literal') result[part.type] = Number(part.value);
        return result;
    }, {});

    const calendarDate = new Date(Date.UTC(parts.year, parts.month - 1, parts.day));
    return {
        ...parts,
        dayName: DAY_NAMES[calendarDate.getUTCDay()]
    };
}

export function zonedDateTimeToUtc({ year, month, day, hour = 0, minute = 0, second = 0 }, timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const targetAsUtc = Date.UTC(year, month - 1, day, hour, minute, second);
    let result = new Date(targetAsUtc);

    // Duas passagens cobrem mudanças de offset próximas a transições de horário de verão.
    for (let attempt = 0; attempt < 2; attempt++) {
        const observed = getZonedDateParts(result, timeZone);
        const observedAsUtc = Date.UTC(
            observed.year,
            observed.month - 1,
            observed.day,
            observed.hour,
            observed.minute,
            observed.second
        );
        result = new Date(result.getTime() + (targetAsUtc - observedAsUtc));
    }

    return result;
}

function addCalendarDays(parts, days) {
    const date = new Date(Date.UTC(parts.year, parts.month - 1, parts.day + days));
    return {
        year: date.getUTCFullYear(),
        month: date.getUTCMonth() + 1,
        day: date.getUTCDate()
    };
}

export function getScheduleClock(now = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = getZonedDateParts(now, timeZone);
    return {
        dayName: parts.dayName,
        time: `${String(parts.hour).padStart(2, '0')}:${String(parts.minute).padStart(2, '0')}`
    };
}

export function getScheduleWeekKey(now = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = getZonedDateParts(now, timeZone);
    const calendarDate = new Date(Date.UTC(parts.year, parts.month - 1, parts.day));
    const day = calendarDate.getUTCDay();
    const monday = addCalendarDays(parts, day === 0 ? -6 : 1 - day);
    return `${monday.year}-${String(monday.month).padStart(2, '0')}-${String(monday.day).padStart(2, '0')}`;
}

export function getNextWeekStart(now = new Date(), timeZone = DEFAULT_SCHEDULE_TIMEZONE) {
    const parts = getZonedDateParts(now, timeZone);
    const calendarDate = new Date(Date.UTC(parts.year, parts.month - 1, parts.day));
    const day = calendarDate.getUTCDay();
    const daysUntilNextMonday = day === 0 ? 1 : 8 - day;
    const nextMonday = addCalendarDays(parts, daysUntilNextMonday);
    return zonedDateTimeToUtc(nextMonday, timeZone);
}

export function addDaysInTimeZone(date, days, timeZone = DEFAULT_SCHEDULE_TIMEZONE, time = '00:00') {
    const parts = getZonedDateParts(date, timeZone);
    const target = addCalendarDays(parts, days);
    const [hour, minute] = time.split(':').map(Number);
    return zonedDateTimeToUtc({ ...target, hour, minute }, timeZone);
}

// ---------------------------------------------------------------------------
// Alocação de horários
//
// A data só é atribuída ao post no momento da aprovação. Até lá o rascunho fica
// sem `scheduledFor`, para que excluir uma ideia no plano ou rejeitar um
// rascunho na revisão não deixe buraco no calendário.
// ---------------------------------------------------------------------------

export const DEFAULT_SLOT_LEAD_MINUTES = 10;
const DEFAULT_SLOT_HORIZON_WEEKS = 12;

function normalizeSlotDays(days) {
    const normalized = (Array.isArray(days) ? days : [])
        .filter(day => DAY_NAMES.includes(day));
    return normalized.length > 0 ? [...new Set(normalized)] : [...DAY_NAMES];
}

function normalizeSlotTimes(times) {
    const normalized = (Array.isArray(times) ? times : [])
        .map(time => (typeof time === 'string' ? time.trim() : ''))
        .filter(time => /^\d{2}:\d{2}$/.test(time));
    return normalized.length > 0
        ? [...new Set(normalized)].sort()
        : ['09:00'];
}

/**
 * Dias e horários configurados para um tipo de conteúdo, já normalizados.
 */
export function getSlotPreferences(schedule = {}, kind = 'post') {
    const normalized = normalizeScheduleConfig(schedule);
    const isStory = kind === 'story';
    return {
        timeZone: normalized.timezone,
        days: normalizeSlotDays(isStory ? normalized.storyPreferredDays : normalized.preferredDays),
        times: normalizeSlotTimes(isStory ? normalized.storyPreferredTimes : normalized.preferredTimes)
    };
}

/**
 * Quantos conteúdos cabem numa semana sem repetir dia+horário.
 */
export function getWeeklySlotCapacity(schedule = {}, kind = 'post') {
    const { days, times } = getSlotPreferences(schedule, kind);
    return days.length * times.length;
}

/**
 * Percorre o cronograma a partir de `from` e devolve os próximos horários
 * livres. `isSlotTaken` marca os horários já ocupados por outros posts; quando
 * a semana enche, a busca continua nas semanas seguintes.
 */
export function findAvailableScheduleSlots({
    schedule = {},
    kind = 'post',
    count = 1,
    from = new Date(),
    isSlotTaken = () => false,
    horizonWeeks = DEFAULT_SLOT_HORIZON_WEEKS,
    leadMinutes = DEFAULT_SLOT_LEAD_MINUTES
} = {}) {
    if (!Number.isFinite(count) || count <= 0) return [];

    const { timeZone, days, times } = getSlotPreferences(schedule, kind);
    const earliest = new Date(from.getTime() + leadMinutes * 60 * 1000);
    const horizonDays = Math.max(7, Math.round(horizonWeeks * 7));
    const found = [];

    for (let daysAhead = 0; daysAhead <= horizonDays && found.length < count; daysAhead++) {
        const dayName = getZonedDateParts(addDaysInTimeZone(from, daysAhead, timeZone), timeZone).dayName;
        if (!days.includes(dayName)) continue;

        for (const time of times) {
            if (found.length >= count) break;
            const slot = addDaysInTimeZone(from, daysAhead, timeZone, time);
            if (slot < earliest) continue;
            if (isSlotTaken(slot)) continue;
            found.push(slot);
        }
    }

    return found;
}
