import { describe, expect, it } from 'vitest';
import { isAutopilotEnabled, isAutoApproveEnabled, getAutopilotSummary } from './schedule';

describe('isAutopilotEnabled', () => {
    it('reads the flag the profile actually stores', () => {
        expect(isAutopilotEnabled({ contentSchedule: { autoGenerationEnabled: true } })).toBe(true);
        expect(isAutopilotEnabled({ contentSchedule: { autoGenerationEnabled: false } })).toBe(false);
    });

    // O banner lia autoGenerateSettings.enabled / autoPostEnabled, que nenhum
    // perfil tem, e por isso anunciava "DESLIGADO" mesmo com o piloto ativo.
    it('ignores the fields the old banner invented', () => {
        expect(isAutopilotEnabled({
            contentSchedule: { autoGenerationEnabled: true },
            autoGenerateSettings: { enabled: false },
            autoPostEnabled: false,
        })).toBe(true);
    });

    it('falls back to the legacy mode when the flag is absent', () => {
        expect(isAutopilotEnabled({ contentSchedule: { autonomyMode: 'manual' } })).toBe(false);
        expect(isAutopilotEnabled({ contentSchedule: { autonomyMode: 'review' } })).toBe(true);
        expect(isAutopilotEnabled({ autonomyMode: 'manual' })).toBe(false);
    });

    it('treats a profile with no schedule as enabled, matching the backend', () => {
        expect(isAutopilotEnabled({})).toBe(true);
    });

    it('survives a missing profile', () => {
        expect(isAutopilotEnabled(null)).toBe(true);
        expect(isAutoApproveEnabled(null)).toBe(false);
    });
});

describe('isAutoApproveEnabled', () => {
    it('requires an explicit opt-in', () => {
        expect(isAutoApproveEnabled({ contentSchedule: { autoApproveFallbackEnabled: true } })).toBe(true);
        expect(isAutoApproveEnabled({ contentSchedule: {} })).toBe(false);
        expect(isAutoApproveEnabled({ contentSchedule: { autoApproveFallbackEnabled: 'sim' } })).toBe(false);
    });
});

describe('getAutopilotSummary', () => {
    // Só os dois interruptores juntos publicam sem ninguém. O banner antigo
    // prometia "postagem automática" com a aprovação automática desligada.
    it('only calls the cycle automatic when generation and approval are both on', () => {
        expect(getAutopilotSummary({
            contentSchedule: { autoGenerationEnabled: true, autoApproveFallbackEnabled: true }
        }).fullyAutomatic).toBe(true);

        expect(getAutopilotSummary({
            contentSchedule: { autoGenerationEnabled: true, autoApproveFallbackEnabled: false }
        })).toMatchObject({ generates: true, publishes: false, fullyAutomatic: false });

        expect(getAutopilotSummary({
            contentSchedule: { autoGenerationEnabled: false, autoApproveFallbackEnabled: true }
        })).toMatchObject({ generates: false, publishes: true, fullyAutomatic: false });
    });

    it('translates the generation slot for display', () => {
        expect(getAutopilotSummary({
            contentSchedule: { autoGenerateDay: 'saturday', autoGenerateTime: '14:45' }
        })).toMatchObject({ generationDay: 'sábado', generationTime: '14:45' });
    });

    it('falls back to the same defaults the backend applies', () => {
        expect(getAutopilotSummary({})).toMatchObject({
            generationDay: 'domingo', generationTime: '20:00', leadHours: 24,
        });
        expect(getAutopilotSummary(null)).toMatchObject({ leadHours: 24 });
    });

    it('ignores a lead time that could never trigger', () => {
        expect(getAutopilotSummary({ contentSchedule: { autoApproveLeadHours: 0 } }).leadHours).toBe(24);
        expect(getAutopilotSummary({ contentSchedule: { autoApproveLeadHours: 48 } }).leadHours).toBe(48);
    });
});
