// Leitura única das flags de automação de um perfil de negócio.
//
// Existiam duas leituras concorrentes no mesmo dashboard: a matriz de controle
// usava `contentSchedule.autoGenerationEnabled` e o banner usava
// `autoGenerateSettings.enabled || autoPostEnabled`, campos que nenhum perfil
// tem. O banner anunciava "DESLIGADO" mesmo com o piloto ativo.
//
// Espelha a normalização do backend (utils/scheduleConfig.js): quando a flag
// nova não existe, o modo legado decide.

export function isAutopilotEnabled(profile) {
    const schedule = profile?.contentSchedule || {};
    if (typeof schedule.autoGenerationEnabled === 'boolean') {
        return schedule.autoGenerationEnabled;
    }
    const legacyMode = schedule.autonomyMode || profile?.autonomyMode;
    return legacyMode !== 'manual';
}

export function isAutoApproveEnabled(profile) {
    return profile?.contentSchedule?.autoApproveFallbackEnabled === true;
}

const WEEKDAYS = {
    sunday: 'domingo', monday: 'segunda', tuesday: 'terça', wednesday: 'quarta',
    thursday: 'quinta', friday: 'sexta', saturday: 'sábado',
};

// Gerar e publicar são interruptores independentes: um perfil pode criar a
// semana inteira sozinho e ainda assim nunca publicar nada sem alguém aprovar.
// O banner tratava os dois como um só e prometia postagem automática que não
// aconteceria. Espelha os padrões de utils/scheduleConfig.js no backend.
export function getAutopilotSummary(profile) {
    const schedule = profile?.contentSchedule || {};
    const generates = isAutopilotEnabled(profile);
    const publishes = isAutoApproveEnabled(profile);

    return {
        generates,
        publishes,
        generationDay: WEEKDAYS[schedule.autoGenerateDay] || WEEKDAYS.sunday,
        generationTime: schedule.autoGenerateTime || '20:00',
        leadHours: Number(schedule.autoApproveLeadHours) > 0 ? Number(schedule.autoApproveLeadHours) : 24,
        // Só a combinação dos dois fecha o ciclo sem intervenção humana.
        fullyAutomatic: generates && publishes,
    };
}
